### ISSUE TITLE
panic: unaligned 64-bit atomic operation

### ISSUE THREAD

**Issue by ubuster** [cybertec-postgresql/pg_timetable#544]
We use TT 5.0 in both 32-bit and 64-bit compiled application under Windows 10. The 64-bit app is starting and runnig normally. But the 32-bit app actually starts as well as good, then stops after a few seconds.
The log looks as follow:

```
2023-02-27 11:23:01.001 [INFO] [sid:1371015148] Starting new session...
2023-02-27 11:23:01.274 [INFO] Database connection established
2023-02-27 11:23:01.394 [INFO] Accepting asynchronous chains execution requests...
2023-02-27 11:23:01.396 [INFO] [count:0] Retrieve scheduled chains to run @reboot
2023-02-27 11:23:01.404 [INFO] [count:0] Retrieve interval chains to run
2023-02-27 11:23:01.416 [INFO] [count:0] Retrieve scheduled chains to run
panic: unaligned 64-bit atomic operation

goroutine 5 [running]:
runtime/internal/atomic.panicUnaligned()
        C:/Program Files/Go/src/runtime/internal/atomic/unaligned.go:8 +0x2d
runtime/internal/atomic.Load64(0x1203427c)
        C:/Program Files/Go/src/runtime/internal/atomic/atomic_386.s:225 +0x10
go.uber.org/atomic.(*Int64).Load(...)
        C:/Program Files/Go/scr/pkg/mod/go.uber.org/atomic@v1.10.0/int64.go:45
github.com/jackc/puddle/v2.(*Pool[...]).Stat(0x12034230)
        C:/Program Files/Go/scr/pkg/mod/github.com/jackc/puddle/v2@v2.1.2/pool.go:269 +0x77
github.com/jackc/pgx/v5/pgxpool.(*Pool).Stat(0x120341c0)
        C:/Program Files/Go/scr/pkg/mod/github.com/jackc/pgx/v5@v5.1.1/pgxpool/pool.go:564 +0x32
github.com/jackc/pgx/v5/pgxpool.(*Pool).checkMinConns(0x120341c0)
        C:/Program Files/Go/scr/pkg/mod/github.com/jackc/pgx/v5@v5.1.1/pgxpool/pool.go:460 +0x21
github.com/jackc/pgx/v5/pgxpool.(*Pool).checkHealth(0x120341c0)
        C:/Program Files/Go/scr/pkg/mod/github.com/jackc/pgx/v5@v5.1.1/pgxpool/pool.go:411 +0x25
github.com/jackc/pgx/v5/pgxpool.(*Pool).backgroundHealthCheck(0x120341c0)
        C:/Program Files/Go/scr/pkg/mod/github.com/jackc/pgx/v5@v5.1.1/pgxpool/pool.go:402 +0xf1
github.com/jackc/pgx/v5/pgxpool.NewWithConfig.func3()
        C:/Program Files/Go/scr/pkg/mod/github.com/jackc/pgx/v5@v5.1.1/pgxpool/pool.go:250 +0x45
created by github.com/jackc/pgx/v5/pgxpool.NewWithConfig
        C:/Program Files/Go/scr/pkg/mod/github.com/jackc/pgx/v5@v5.1.1/pgxpool/pool.go:248 +0x2c4_
```

It seems like you don't seem to assume that the application can be compiled as 32-bit. 
Thanks in advance for any advice.

Tomas

**Comment by pashagolub** [comment]
Hello. 

According to the stack trace you've provided the problem is either in the https://github.com/jackc/puddle/ or in the https://github.com/uber-go/atomic. You may want to create bug report for these projects.

There is nothing we can do about it. Mainly because we have no environment to check 32-bit binaries.

**Comment by ubuster** [comment]
Thanks anyway.
